name: todo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.3.8
  flutter_local_notifications: ^15.1.0+1
  intl: ^0.18.1
  google_fonts: ^5.1.0
  date_picker_timeline: ^1.2.3
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^2.0.7
  rxdart: ^0.27.2
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7
  speech_to_text: ^6.6.2
  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  drift_dev: ^2.15.0
  build_runner: ^2.4.9

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg

